### DISCUSSION TITLE
nut_webgui on kubernetes

### DISCUSSION THREAD

**Discussion by linux24365** [SuperioOne/nut_webgui#19] [Q&A]
Good Morning,
Sorry to bother you, but I need some help / guidance. I am trying to setup nut_webgui on Kubernetes using the example you provided. I am just wondering what would be the port to access the http page. ( I tried 80 , 9000 without success) . Either I get "no server available " or "no page found". The port 3493 conncetion to my external network UPS tool server seems to work according to the pod logs 
Thanks

**Comment by SuperioOne** [comment]
Default port for web UI  is 9000, unless `PORT`  environment variable has a different value.

Do you have any ingress or service configuration to expose nut_webgui's HTTP port? Normally, I didn't include them in the example since there are too many options.

Most basic one looks something like this, but you still need an ingress config, or use different [service type](https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types).
```yaml
apiVersion: v1
kind: Service
metadata:
  name: nutwebgui-service
spec:
  type: ClusterIP
  selector:
    app: nutweb-pod
  ports:
  - port: 80
    targetPort: 9000
```

For troubleshooting, I would use the `kubectl port-forward` command to see if Pod is accessible via service or deployment.  

```shell
# Exposes deployment port (9000) on localhost:9000
kubectl port-forward deployments/nutweb-deployment 9000:9000

# Exposes service port (80) on localhost:9000
kubectl port-forward services/nutwebgui-service 80:9000
```


Also, feel free to ask anytime :+1:
