### ISSUE TITLE
passwords with # are not usable?

### ISSUE THREAD

**Issue by sdetweil** [SuperioOne/nut_webgui#14]
```
docker-compose up
ERROR: yaml.scanner.ScannerError: while scanning a double-quoted scalar
  in "./docker-compose.yml", line 14, column 18
found unknown escape character '#'
  in "./docker-compose.yml", line 14, column 25
```

password is "test#1234%$!"

con get it thru docker-compose if I escape the # 
but your code doesn't like it 

doesn't like the %$!  either

took out the special chars, then it works ok

**Comment by SuperioOne** [comment]
I've changed my own server upsd.user password with `test#1234%$!` to see if any special character causes issue to `server_start.sh`. But, both podman-compose and docker-compose seems working?

Tested configs: 

/etc/nut/upsd.users
```
[myupsuser]
  password = test#1234%$!
  instcmds = all
```

docker-compose.yaml
```yaml
version: "3.3"
services:
  nutweb:
    image: ghcr.io/superioone/nut_webgui:latest
    restart: always
    ports:
        - 9000:9000
    environment:
      UPSD_ADDR: "10.0.0.1"
      UPSD_PORT: "3493"
      UPSD_USER: "myupsuser"
      UPSD_PASS: "test#1234%$!"
      PORT: "9000"
```
