### ISSUE TITLE
Feature Request: Add support for secrets when using Docker Compose

### ISSUE THREAD

**Issue by iainchesworth** [SuperioOne/nut_webgui#6]
When using Docker compose ([as described here](https://docs.docker.com/compose/how-tos/use-secrets/)), the password for the UPS monitor user needs to be passed in via an environment variable in the YAML.

It would be great to be able to use Docker secrets [as shown in the Docker documentation](https://docs.docker.com/compose/how-tos/use-secrets/) to inject the password.  Then, passwords would not need to be stored in the Docker compose file; this is a benefit when using GitOps or other CI/CD flows.

Example using Docker secrets:

``` yaml
secrets:
  nut-webgui-password:
    # See https://docs.docker.com/compose/use-secrets/
    file: /home/nut-webgui/nut-webgui-password.txt

services:
  nut-webgui:
    image: ghcr.io/superioone/nut_webgui:latest
    restart: always
    ports:
      - 80:1234
    environment:
      POLL_FREQ: "60"
      POLL_INTERVAL: "5"
      UPSD_ADDR: "myhost"
      UPSD_PORT: "1234"
      UPSD_USER: "admin"
      LISTEN: "0.0.0.0"
      PORT: "1234"
      LOG_LEVEL: "debug"
    secrets:
      - nut-webgui-password
```

In this example, the UPSD_USER's password would be loaded from `/run/secrets/nut-webgui-password`
